<a href="https://colab.research.google.com/github/Dobee-Kim/kusitms/blob/master/Coursera_2%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadcasting example

In [5]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 0.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    0. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  68.9]


In [7]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 98.69375907]
 [ 2.03389831 43.51464435 33.46203346  0.        ]
 [ 3.05084746 56.48535565 63.70656371  1.30624093]]


# A Note on Python/Numpy Vectors

In [8]:
import numpy as np

a = np.random.randn(5)

In [9]:
print(a)

[ 0.58244944  0.38582492 -1.15484635  1.51433063 -0.33720529]


In [11]:
print(a.shape) # row vector도 column vector도 아님

(5,)


In [14]:
print(a.T)

[ 0.58244944  0.38582492 -1.15484635  1.51433063 -0.33720529]


In [15]:
print(np.dot(a,a.T))

4.22868298301478


In [17]:
a = np.random.randn(5,1)
print(a)

[[-0.86165089]
 [-0.53234981]
 [-0.31950655]
 [-1.09699963]
 [-1.98322449]]


In [19]:
print(a.T)

[[-0.86165089 -0.53234981 -0.31950655 -1.09699963 -1.98322449]]


In [20]:
print(np.dot(a,a.T))

[[0.74244226 0.45869969 0.27530311 0.94523071 1.70884716]
 [0.45869969 0.28339632 0.17008925 0.58398754 1.05576917]
 [0.27530311 0.17008925 0.10208444 0.35049857 0.63365322]
 [0.94523071 0.58398754 0.35049857 1.20340818 2.17559653]
 [1.70884716 1.05576917 0.63365322 2.17559653 3.93317939]]


In [24]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b 
print(a)
print(b)
print(c)

[[ 0.60867077 -0.95815743  1.67936694]
 [ 1.15791685  1.10480104  1.0556783 ]
 [ 0.02569102 -0.59070253 -1.33212797]]
[[ 0.53450697]
 [-0.21784588]
 [-0.27923843]]
[[ 0.32533877 -0.51214182  0.89763333]
 [-0.25224741 -0.24067635 -0.22997517]
 [-0.00717392  0.16494684  0.37198132]]


In [25]:
0.60867077 * 0.53450697

0.3253387690002669